json.id beer.id
json.name beer.name
json.style beer.style
json.abv beer.abv
json.ibu beer.ibu
json.srm beer.srm
json.description beer.description
json.glassware beer.glassware
json.image beer.image
json.formats beer.formats